canonifyURLs = true
baseURL = "https://dgraph.io/docs/cloud/"
languageCode = "en-us"
theme = "hugo-docs"
relativeURLs = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "vs"
tabWidth = 4

[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 2

# set by build script: title, baseurl
title = "Dgraph Cloud Docs"

[[menu.main]]
  name = "GraphQL Docs"
  url = "https://dgraph.io/docs/graphql/"
  identifier = "graphql"
  weight = 12

[[menu.main]]
  name = "DQL Docs"
  url = "https://dgraph.io/docs/dql/"
  identifier = "dql"
  weight = 10

[params]
discourse = "https://discuss.dgraph.io/"
site = "cloud-docs"
